name: BlockItem
version: @version@
main: space.mori.blockitem.BlockItem
api-version: 1.14
author:
  - dalbodeule
permissions:
  blockitem.use:
    default: op
    children:
      - blockitem.bow
      - blockitem.crossbow
      - blockitem.wooden_axe,
      - blockitem.wooden_hoe,
      - blockitem.wooden_pickaxe,
      - blockitem.wooden_shovel,
      - blockitem.wooden_sword,
      - blockitem.stone_axe,
      - blockitem.stone_hoe,
      - blockitem.stone_pickaxe,
      - blockitem.stone_shovel,
      - blockitem.stone_sword,
      - blockitem.iron_axe,
      - blockitem.iron_hoe,
      - blockitem.iron_pickaxe,
      - blockitem.iron_shovel,
      - blockitem.iron_sword,
      - blockitem.golden_axe,
      - blockitem.golden_hoe,
      - blockitem.golden_pickaxe,
      - blockitem.golden_shovel,
      - blockitem.golden_sword,
      - blockitem.diamond_axe,
      - blockitem.diamond_hoe,
      - blockitem.diamond_pickaxe,
      - blockitem.diamond_shovel,
      - blockitem.diamond_sword
      - blockitem.bow
      - blockitem.crossbow
  blockitem.armor:
    default: op
    children:
      - blockitem.turtle_helmet
      - blockitem.leather_helmet
      - blockitem.leather_chestplate
      - blockitem.leather_leggings
      - blockitem.leather_boots
      - blockitem.chainmail_helmet
      - blockitem.chainmail_chestplate
      - blockitem.chainmail_leggings
      - blockitem.chainmail_boots
      - blockitem.iron_helmet
      - blockitem.iron_chestplate
      - blockitem.iron_leggings
      - blockitem.iron_boots
      - blockitem.golden_helmet
      - blockitem.golden_chestplate
      - blockitem.golden_leggings
      - blockitem.golden_boots
      - blockitem.diamond_helmet
      - blockitem.diamond_chestplate
      - blockitem.diamond_leggings
      - blockitem.diamond_boots
      - blockitem.elytra